name = "apr-artist-agency"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
NODE_ENV = "production"
KEYSTATIC_GITHUB_CLIENT_ID = "Iv23liwzQw2up9aHVlWj"
PUBLIC_KEYSTATIC_GITHUB_APP_SLUG = "apr-artist-agency-cms"
