# File: .github/workflows/deploy.yml
# Description: Build and deploy an Astro site to GitHub Pages using withastro/action.

name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ] # Adjust branch name if needed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Ensures only one deployment runs at a time for the 'pages' group
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Output the deployment URL

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Uses the official Astro action to handle setup, build, and deployment
      - name: Deploy to GitHub Pages
        id: deployment
        uses: withastro/action@v2
        # No 'with:' options needed for standard GitHub Pages deployment


